# Please refer to instructions here -> https://github.com/mongodb/mongodb-kubernetes-operator
# or this one -> https://adamtheautomator.com/mongodb-kubernetes/
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "5.0.11"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: frogfoot
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: frogfoot-password
      roles:
        - db: "admin"
          name: "clusterAdmin"
        - db: "admin"
          name: "userAdminAnyDatabase"
        - db: "admin"
          name: "readWrite"
        - db: "admin"
          name: "userAdminAnyDatabase"
        - db: "account"
          name: "clusterAdmin"
        - db: "account"
          name: "userAdminAnyDatabase"
        - db: "account"
          name: "readWrite"
        - db: "account"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: frogfoot
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              ports:
                - containerPort: 27017
              resources:
                limits:
                  cpu: 0.25
                  memory: 350M
                requests:
                  cpu: 0.25
                  memory: 350M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 0.25
                  memory: 350M
                requests:
                  cpu: 0.25
                  memory: 350M