apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - name: application
        image: auth-poc/auth
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000