apiVersion: v1
kind: Service
metadata:
  name: auth-poc-user-service
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
    description: Practice Kubernetes Service
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 31002
      port: 8002
      targetPort: 8002
    - name: rpc
      nodePort: 30002
      port: 30002
      targetPort: 30002
  selector:
    app: auth-poc-user