version: '3.1'
services:
  auth:
    image: "ubuntu:14.04"
    build:
      context: .
      dockerfile: DockerFile
    container_name: auth
    volumes:
      - ./../bin/auth/:/usr/local/bin
    ports:
      - "8001:8001"
      - "30001:30001"
    depends_on:
      - mongodb
    links:
      - mongodb
    command: tail -f /dev/null
    environment:
      - TZ=Asia/Jakarta

  user:
    image: "ubuntu:14.04"
    build:
      context: .
      dockerfile: DockerFile
    container_name: user
    volumes:
      - ./../bin/user/:/usr/local/bin
    ports:
      - "8002:8002"
      - "30002:30002"
    depends_on:
      - mongodb
    links:
      - mongodb
    command: tail -f /dev/null
    environment:
      - TZ=Asia/Jakarta

  mongodb:
    image: mongo:5.0.11
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongomongo
      - MONGO_INITDB_ROOT_PASSWORD=sekritz

