HTTP_HOST: "localhost"
HTTP_PORT: "8002"
MONGODB_URI: "mongodb+srv://my-user:donttellanyone@mongodb-svc.mongodb.svc.cluster.local/admin?replicaSet=mongodb&ssl=false"
RPC_DEFAULT_HOST: "localhost"
RPC_PORT_USER_APP: "30002"
RPC_AUTH_SERVICE: "50001"