HTTP_HOST: "0.0.0.0"
HTTP_PORT: "8002"
MONGODB_URI: "mongodb+srv://frogfoot:donttellanyone@mongodb-svc.mongodb.svc.cluster.local/account?authSource=admin&replicaSet=mongodb&ssl=false"
RPC_AUTH_HOST: "auth-poc-auth-service.mongodb.svc.cluster.local"
RPC_AUTH_SERVICE: "30001"
RPC_DEFAULT_HOST: "0.0.0.0"
RPC_PORT_USER_APP: "30002"