HTTP_HOST: "localhost"
HTTP_PORT: "8002"
MONGODB_URI: "mongodb://localhost:27017/?ssl=false"
RPC_AUTH_HOST: "localhost"
RPC_AUTH_SERVICE: "30001"
RPC_DEFAULT_HOST: "localhost"
RPC_PORT_USER_APP: "30002"