apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-poc-auth-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: auth-poc-auth-service
          servicePort: 31001