apiVersion: v1
kind: Service
metadata:
  name: auth-poc-auth-service
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
    description: Practice Kubernetes Service
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 80
      port: 8001
      targetPort: 8001
    - name: https
      nodePort: 443
      port: 8001
      targetPort: 8001
    - name: rpc
      nodePort: 30001
      port: 30001
      targetPort: 30001
  selector:
    app: auth-poc-auth