HTTP_HOST: "localhost"
HTTP_PORT: "8001"
MONGODB_URI: "mongodb+srv://mongodb-service.mongodb.svc.cluster.local?ssl=false"
RPC_DEFAULT_HOST: "localhost"
RPC_PORT_AUTH_APP: "30001"
RPC_USER_SERVICE: "50002"